spring:
  datasource:
    url: jdbc:mysql://192.168.33.11:3306/task-engine?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: Pzk2020@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000


taki:
  tend:
    consistency:
      parallel:
        pool:
          thread-max-pool-size: 6
          thread-core-pool-size: 6
          thread-pool-keep-alive-time: 60
          thread-pool-keep-alive-time-unit: SECONDS
          thread-pool-queue-size: 200
          # 框架自身有默认的实现类 来扫描查询任务的开始时间以及结束时间 这里给出指定出定制化的实现类
          #thread-schedule-time-range-class-name: com.taki.demo.range.MyTaskTimeRangeQueury
      action:
        fail-count-threadshold: 0
      shard:
        task-sharded: false